apiVersion: v1
kind: Service
metadata:
  name: fleet-tracking-system-service
spec:
  type: NodePort
  selector:
    app: fleet-tracking-system
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 30080