apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fleet-tracking-system
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=ghcr.io/peler1nl1kelt0s/fleet-tracking-system-frontend:latest,backend=ghcr.io/peler1nl1kelt0s/fleet-tracking-system-backend:latest
    argocd-image-updater.argoproj.io/frontend.update-strategy: digest
    argocd-image-updater.argoproj.io/backend.update-strategy: digest
spec:
  project: default
  source:
    repoURL: https://github.com/peler1nl1kelt0s/fleet-tracking-system.git
    targetRevision: dev
    path: k3s
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
