apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/peler1nl1kelt0s/fleet-tracking-system-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: API_PORT
          value: "3000"
        - name: WS_PORT
          value: "3001"
        - name: MQTT_BROKER_URL
          value: "mqtt://localhost:1883"
        - name: OPENSKY_BASE_URL
          value: "https://opensky-network.org/api/states/all"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: dev
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
