apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev
  labels:
    app: backend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/peler1nl1kelt0s/fleet-tracking-system-backend:2cea2b59a513f1506594923bc6dac1cdff94b0b6
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: API_PORT
          value: "3000"
        - name: WS_PORT
          value: "3001"
        - name: MQTT_BROKER_URL
          value: "mqtt://mosquitto:1883" 
        - name: OPENSKY_BASE_URL
          value: "https://opensky-network.org/api/states/all"
        - name: REDIS_URL
          value: "redis://redis:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: dev
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP