apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev
  labels:
    app: backend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/peler1nl1kelt0s/fleet-tracking-system-backend:9f7368535de404aaea8e39ccd127ba80c03fd3e4
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: API_PORT
          value: "3000"
        - name: WS_PORT
          value: "3001"
        - name: MQTT_BROKER_URL
          value: "mqtt://localhost:1883"
        - name: OPENSKY_BASE_URL
          value: "https://opensky-network.org/api/states/all"
        - name: OPENSKY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: opensky-secret
              key: client-id
        - name: OPENSKY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: opensky-secret
              key: client-secret
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: POSTGRES_HOST
          value: "postgres.dev.svc.cluster.local"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "fleet_tracking"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: POSTGRES_PORT
          value: "5432"
        volumeMounts:
        - mountPath: /app/src
          name: source-code
      volumes:
      - name: source-code
        hostPath:
          path: /home/peler1nl1kelt0s/Desktop/fleet-tracking-system/back-end/src
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: dev
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP