apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev
  labels:
    app: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
<<<<<<< HEAD
        image: ghcr.io/peler1nl1kelt0s/fleet-tracking-system-frontend:5ccf4e0196437a3edfa0562cf0d2dcf579348d8c
=======
        image: ghcr.io/peler1nl1kelt0s/fleet-tracking-system-frontend:5ccf4e0196437a3edfa0562cf0d2dcf579348d8c
>>>>>>> be2288b (Update image tags to 450efc8a840e0feffd3f183ad0f8475e3fe69b7d)
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: dev
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
  type: LoadBalancer